name: Sendspin Client
slug: sendspin
description: Sendspin / Resonate audio client
version: "0.1.1"
arch:
  - aarch64
  - armv7
  - amd64
startup: services
boot: auto
host_network: true
audio: true
options:
  name: "Sendspin Player"
  server_ip: ""
  port: 8080
schema:
  name: str
  server_ip: str?
  port: int?
